services:
  client:
    privileged: true
    build: .
    cap_add:
      - net_admin
    volumes:
      - .:/src
    sysctls:
      - net.ipv4.ip_forward=1
    restart: always
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - WG_ROLE=client
    ports:
      - 51820
  server:
    privileged: true
    build: .
    cap_add:
      - net_admin
    volumes:
      - .:/src
    sysctls:
      - net.ipv4.ip_forward=1
    restart: always
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - WG_ROLE=server
    ports:
      - 51820
